import { I18N } from '../lang/i18n.enum';

export enum ACCOUNT_ROLE {
  ADMIN,
  SUPERADMIN,
}

export enum PRICE_OPTIONS {
  VALUE,
  PERCENTAGE,
}

export enum SETTING_TYPE {
  SPECIAL_REQUEST,
  DYNAMIC_POPUP,
  PRICING,
  QR_TEXT,
  FB_TEXT,
  FB_LINK,
  EMAIL,
  PHONE_NUMBER,
  COMPANY_NAME,
  DEFAULT_COLOR,
  MONTHLY_ORDER,
  AUTO_VERIFY_ORDER,
  TRUCK_POOL,
}

export enum COLORS {
  PINK = 'pink',
  YELLOW = 'yellow',
  ORANGE = 'orange',
  GREEN = 'green',
  BLUE = 'blue',
  GREY = 'grey',
  DARK_GREEN = 'dark_green',
  BLACK = 'black',
}

export enum DYNAMIC_DEFAULT_OPTION {
  FORKLIFT = 'Require forklift driver',
  MIXED = 'Allow mixed loading',
}

export enum DEFAULT_TRUCK_PAYLOAD {
  ANY,
  LESS_THAN_ONE,
  ONE_TO_TWO,
  TWO_TO_THREE,
  THREE_TO_FOUR,
  FIVE_TO_SIX,
  SIX_TO_EIGHT,
  EIGHT_TO_TEN,
  TEN_TO_FIFTEEN,
  FIFTEEN_TO_TWENTY,
  TWENTY_TO_TWENTY_FIVE,
  TWENTY_FIVE_TO_THIRTY,
  MORE_THAN_THIRTY,
}

export enum DEFAULT_CONTAINER_SIZE {
  NO = '',
  SIZE_2x20 = '2x20',
  SIZE_20 = '20',
  SIZE_40 = '40',
  SIZE_45 = '45',
}

export enum DEFAULT_NON_MOTORIZED_PAYLOAD {
  LESS_THAN_THREE_KG = 'less_than_3kg',
  THREE_TO_TEN_KG = '3_10kg',
  TEN_TO_TWENTY_FIVE_KG = '10_25kg',
  TWENTY_FIVE_TO_FIFTY_KG = '25_50kg',
  FIFTY_TO_ONE_HUNDRED_KG = '50_100kg',
  ONE_HUNDRED_TO_FIVE_HUNDRED_KG = '100_500kg',
  MORE_THAN_FIVE_HUNDRED_KG = 'more_than_500kg',
}

export enum DEFAULT_CONCATENATED_GOODS_PAYLOAD {
  ANY = 'ANY',
}

export enum DEFAULT_CONTRACT_CAR_PAYLOAD {
  ANY = 'ANY',
}

export const truckPayloadAdmin = [
  {
    key: '',
    label: I18N.DEFAULT_CHOOSE_TRUCK_LOAD_LABEL,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.ANY,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_ANY,
  },
  {
    key: DEFAULT_NON_MOTORIZED_PAYLOAD.LESS_THAN_THREE_KG,
    label: I18N.DEFAULT_NON_MOTORIZED_LESS_THAN_THREE,
  },
  {
    key: DEFAULT_NON_MOTORIZED_PAYLOAD.THREE_TO_TEN_KG,
    label: I18N.DEFAULT_NON_MOTORIZED_THREE_TO_TEN,
  },
  {
    key: DEFAULT_NON_MOTORIZED_PAYLOAD.TEN_TO_TWENTY_FIVE_KG,
    label: I18N.DEFAULT_NON_MOTORIZED_TEN_TO_TWENTY_FIVE,
  },
  {
    key: DEFAULT_NON_MOTORIZED_PAYLOAD.TWENTY_FIVE_TO_FIFTY_KG,
    label: I18N.DEFAULT_NON_MOTORIZED_TWENTY_FIVE_TO_FIFTY,
  },
  {
    key: DEFAULT_NON_MOTORIZED_PAYLOAD.FIFTY_TO_ONE_HUNDRED_KG,
    label: I18N.DEFAULT_NON_MOTORIZED_FIFTY_TO_ONE_HUNDRED,
  },
  {
    key: DEFAULT_NON_MOTORIZED_PAYLOAD.ONE_HUNDRED_TO_FIVE_HUNDRED_KG,
    label: I18N.DEFAULT_NON_MOTORIZED_ONE_HUNDRED_TO_FIVE_HUNDRED,
  },
  {
    key: DEFAULT_NON_MOTORIZED_PAYLOAD.MORE_THAN_FIVE_HUNDRED_KG,
    label: I18N.DEFAULT_NON_MOTORIZED_MORE_THAN_FIVE_HUNDRED,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.LESS_THAN_ONE,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_LESS_THAN_ONE,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.ONE_TO_TWO,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_ONE_TO_TWO,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.TWO_TO_THREE,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_TWO_TO_THREE,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.THREE_TO_FOUR,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_THREE_TO_FOUR,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.FIVE_TO_SIX,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_FIVE_TO_SIX,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.SIX_TO_EIGHT,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_SIX_TO_EIGHT,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.EIGHT_TO_TEN,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_EIGHT_TO_TEN,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.TEN_TO_FIFTEEN,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_TEN_TO_FIFTEEN,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.FIFTEEN_TO_TWENTY,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_FIFTEEN_TO_TWENTY,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.TWENTY_TO_TWENTY_FIVE,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_TWENTY_TO_TWENTY_FIVE,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.TWENTY_FIVE_TO_THIRTY,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_TWENTY_FIVE_TO_THIRTY,
  },
  {
    key: DEFAULT_TRUCK_PAYLOAD.MORE_THAN_THIRTY,
    label: I18N.DEFAULT_TRUCK_PAYLOAD_MORE_THAN_THIRTY,
  },
  {
    key: DEFAULT_CONTAINER_SIZE.SIZE_20,
    label: I18N.SETTINGS_CONT_20,
  },
  {
    key: DEFAULT_CONTAINER_SIZE.SIZE_40,
    label: I18N.SETTINGS_CONT_40,
  },
  {
    key: DEFAULT_CONTAINER_SIZE.SIZE_45,
    label: I18N.SETTINGS_CONT_45,
  },
];

export enum DISPLAY_ON {
  CUSTOMER = 'CUSTOMER',
  TRUCKOWNER = 'TRUCKOWNER',
}

export enum BLACK_BOX_TYPE {
  DINH_VI_HOP_QUY = 'DINH_VI_HOP_QUY',
  ANTECK = 'ANTECK',
  VIETMAP = 'VIETMAP',
}
